package com.example.myapplication

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.enableEdgeToEdge
import androidx.compose.foundation.Image
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.Button
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.unit.dp
import com.example.myapplication.ui.theme.MyApplicationTheme
import kotlin.random.Random

data class FilmModel(
    val id: String,
    val posterUrl: String,
    val name: String,
    val description: String?,
    val releaseDate: Int
)

object DataRepository {
    var filmsList: List<FilmModel> = emptyList()
}

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()

        setContent {
            MyApplicationTheme {
                var currentScreen by remember { mutableStateOf("first") }

                if (currentScreen == "first") {
                    FirstScreen(
                        onOpenSecondScreen = {
                            currentScreen = "second"
                        }
                    )
                } else {
                    SecondScreen()
                }
            }
        }
    }
}

@Composable
fun FirstScreen(onOpenSecondScreen: () -> Unit) {
    var userInput by remember { mutableStateOf("") }
    var isGenerated by remember { mutableStateOf(false) }

    val count = userInput.toIntOrNull()
    val canGenerate = count != null && count > 0

    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(16.dp)
    ) {
        Text(
            text = "Первый экран",
            style = MaterialTheme.typography.headlineSmall
        )

        Spacer(modifier = Modifier.height(16.dp))

        OutlinedTextField(
            value = userInput,
            onValueChange = { newValue ->
                userInput = newValue
                isGenerated = false
            },
            label = { Text("Введите положительное число") }
        )

        Spacer(modifier = Modifier.height(16.dp))

        Button(
            enabled = canGenerate,
            onClick = {
                DataRepository.filmsList = generateFilms(count ?: 0)
                isGenerated = true
            }
        ) {
            Text("Сгенерировать")
        }

        Spacer(modifier = Modifier.height(16.dp))

        Button(
            enabled = isGenerated,
            onClick = {
                onOpenSecondScreen()
            }
        ) {
            Text("Открыть второй экран")
        }
    }
}

fun generateFilms(count: Int): List<FilmModel> {
    val names = listOf(
        "Shutter Island",
        "Inception",
        "Blood Diamond",
        "Snatch",
        "Interstellar",
        "Avatar",
        "Titanic",
        "Gladiator",
        "The Matrix",
        "Fight Club"
    )

    return List(count) { index ->
        FilmModel(
            id = index.toString(),
            posterUrl = "poster_$index",
            name = names.random(),
            description = "Описание фильма",
            releaseDate = Random.nextInt(1990, 2025)
        )
    }
}

@Composable
fun SecondScreen() {
    var filterInput by remember { mutableStateOf("") }
    var filteredFilms by remember { mutableStateOf(DataRepository.filmsList) }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(16.dp)
    ) {
        Text(
            text = "Второй экран",
            style = MaterialTheme.typography.headlineSmall
        )

        Spacer(modifier = Modifier.height(16.dp))

        OutlinedTextField(
            value = filterInput,
            onValueChange = { newValue ->
                filterInput = newValue
            },
            label = { Text("Введите год") }
        )

        Spacer(modifier = Modifier.height(16.dp))

        Button(
            onClick = {
                val year = filterInput.toIntOrNull()

                filteredFilms = if (filterInput.isBlank()) {
                    DataRepository.filmsList
                } else if (year != null) {
                    DataRepository.filmsList.filter { film ->
                        film.releaseDate <= year
                    }
                } else {
                    emptyList()
                }
            }
        ) {
            Text("Сортировать")
        }

        Spacer(modifier = Modifier.height(16.dp))

        if (filteredFilms.isEmpty()) {
            Text("Нет подходящих фильмов")
        } else {
            LazyColumn {
                items(filteredFilms) { film ->
                    FilmItem(film)
                }
            }
        }
    }
}

@Composable
fun FilmItem(film: FilmModel) {
    Row(
        modifier = Modifier
            .padding(8.dp)
    ) {
        Image(
            painter = painterResource(id = android.R.drawable.ic_menu_gallery),
            contentDescription = "Film image",
            modifier = Modifier.size(80.dp)
        )

        Spacer(modifier = Modifier.width(16.dp))

        Column {
            Text(text = film.name)
            Text(text = "Год: ${film.releaseDate}")
        }
    }
}